### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by kambala-decapitator** [macmade/IOBrowser#1]
It'd be convenient to have:
- toggle data view between base64 and raw bytes (also possibly convert to decimal number for lengths 1/2/4/8)
- toggle integer numbers view between decimal and hexadecimal

**Comment by macmade** [comment]
Thanks a lot for the suggestion.  
This is indeed quite convenient.

These features have been implemented in 4d2ba48f180b91393f2eac0fa7d4a0d68067f4a4.

I've attached a preview build, so you can test.  
Please tell me if this is OK for you.
[IOBrowser.app.zip](https://github.com/macmade/IOBrowser/files/10221525/IOBrowser.app.zip)

**Comment by kambala-decapitator** [comment]
thanks a lot, works great!

just thought of a few more improvements:
- remember user-configured columns width
- ability to copy keys and values (at least separately)

**Comment by macmade** [comment]
Here you go, version 1.2.0 is now available: https://github.com/macmade/IOBrowser/releases/tag/1.2.0

Thanks a lot for the suggestions!

**Comment by kambala-decapitator** [comment]
thank you very much!

but I don't think I understand how to use the copy feature: when I press Cmd+C (or respective menu command), I can't paste into TextMate or Terminal. In Apple's Clipboard Viewer I see the following, but both entries have 0 bytes:

![Screenshot 2022-12-15 at 09 39 23](https://user-images.githubusercontent.com/1557784/207790340-affed258-140f-4037-998c-7711748ddad5.png)

**Comment by macmade** [comment]
Ha, made a last minute typo… 😖
I’ll publish a fix.

**Comment by macmade** [comment]
Version 1.2.1 is now available: https://github.com/macmade/IOBrowser/releases/tag/1.2.1

**Comment by kambala-decapitator** [comment]
now it's perfect :) Thank you!
